### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by znck** [znck/keynote#5]
- [ ] API to render transitions/effects e.g. elements appearing, animating or leaving in response to some user action
- [ ] Robust slide transitions
- [ ] Pointer/clicker support
- [ ] Ability to write presentations in  markdown
- [ ] Increase API fluency
- [ ] Mobile support and optimized build for screen size
